### ISSUE TITLE
ValueError: offset must be non-negative and no greater than buffer length 

### ISSUE THREAD

**Issue by murthyrudra** [IBM/dolomite-engine#53]
Hi, I have a very large `jsonl` file which I have converted to the memory mapped indexed dataset using `tools/megatron_dataset/preprocess_data.py` script. The code ran successfully without any errors. However, when I try to find the number of tokens in the final data using the script `tools/megatron_dataset/iterate_preprocessed_data.py` I am getting the following error

```bash
2024-10-27 20:43:55,127 - [INFO    ] ▶ Load the _IndexReader from data/eng.idx
2024-10-27 20:43:55,161 - [INFO    ] ▶  Extract the sequence lengths
2024-10-27 20:43:55,161 - [INFO    ] ▶  Extract the sequence pointers
2024-10-27 20:43:55,162 - [INFO    ] ▶  Extract the document indices
2024-10-27 20:43:55,186 - [INFO    ] ▶ > total number of sequences: 34903181
2024-10-27 20:43:55,186 - [INFO    ] ▶ > total number of documents: 34903181
2024-10-27 20:43:55,187 - [INFO    ] ▶ number of documents in the dataset = 34903181
  3%|███▌                                                                                                                                      | 893319/34903181 [00:03<01:54, 295923.18it/s]
Traceback (most recent call last):
  File "~/dolomite-engine/tools/megatron_dataset/iterate_preprocessed_data.py", line 47, in <module>
    main()
  File "~/dolomite-engine/tools/megatron_dataset/iterate_preprocessed_data.py", line 40, in main
    for document in tqdm(dataset):
  File "/usr/shared/conda/dolomite/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "~/dolomite-engine/dolomite_engine/data/megatron/indexed_dataset.py", line 444, in __getitem__
    sequence = numpy.frombuffer(
               ^^^^^^^^^^^^^^^^^
ValueError: offset must be non-negative and no greater than buffer length (121278325996)


```

**Comment by shawntan** [comment]
Can you list the commands you ran? Downloaded and processed the data, and got no errors.

**Comment by murthyrudra** [comment]
Hi, 
I've included for you the repo containing the scripts. 

```bash
python extract_sangraha.py --output <path to output folder>
```

Once the dataset was downloaded I ran the preprocessing script as follows
```
python tools/megatron_dataset/preprocess_data.py --input <path to downloaded jsonl file> --tokenizer meta-llama/Meta-Llama-3.1-8B --append-eod --workers 8 --output-prefix <path to save the processed data> --chunk-size 10000    
```

To validate the processing was done correctly, I am running the following script to get total number of tokens
```
python tools/megatron_dataset/iterate_preprocessed_data.py --path-prefix <path to save the processed data>
```

**Comment by mayank31398** [comment]
I think @shawntan has used the same scripts you shared with me.
Can you check @shawntan ?

**Comment by shawntan** [comment]
Yup I did exactly this. No errors.
Relevant library versions:
```
open_clip_torch==2.26.1
pytorch-lightning==2.0.7
pytorch-triton==3.1.0+cf34004b8a
torch==2.6.0.dev20241014+cu124
torchaudio==2.5.0.dev20241014+cu124
torchdiffeq==0.2.4
torchmetrics==1.4.1
torchsde==0.2.6
torchvision==0.20.0.dev20241014+cu124
numpy==2.1.2
```

**Comment by murthyrudra** [comment]
Thanks, changing the numpy version resolved the issue.
