### ISSUE TITLE
Issue with Fine-tuning Llama 3.1 8B model

### ISSUE THREAD

**Issue by murthyrudra** [IBM/dolomite-engine#58]
Hi, I am fine-tuning the Llama 3.1 8B model using the dolomite engine. I am getting the following error
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/user/IBM/dolomite_new/dolomite-engine/dolomite_engine/finetune.py", line 303, in <module>
[rank0]:     main()
[rank0]:   File "/user/IBM/dolomite_new/dolomite-engine/dolomite_engine/finetune.py", line 288, in main
[rank0]:     train(
[rank0]:   File "/user/IBM/dolomite_new/dolomite-engine/dolomite_engine/finetune.py", line 97, in train
[rank0]:     loss_step_dict = train_step(
[rank0]:                      ^^^^^^^^^^^
[rank0]:   File "/user/IBM/dolomite_new/dolomite-engine/dolomite_engine/train_utils.py", line 71, in train_step
[rank0]:     loss_micro_step_dict["loss"].backward()
[rank0]:   File "/user/shared/conda/dolomite/lib/python3.11/site-packages/torch/_tensor.py", line 581, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/user/shared/conda/dolomite/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/user/shared/conda/dolomite/lib/python3.11/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/user/shared/conda/dolomite/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 1129, in unpack_hook
[rank0]:     frame.check_recomputed_tensors_match(gid)
[rank0]:   File "/user/shared/conda/dolomite/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 903, in check_recomputed_tensors_match
[rank0]:     raise CheckpointError(
[rank0]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
[rank0]: tensor at position 16:
[rank0]: saved metadata: {'shape': torch.Size([1, 32, 174, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([1, 32, 348, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 18:
[rank0]: saved metadata: {'shape': torch.Size([1, 32, 174, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([1, 32, 348, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 21:
[rank0]: saved metadata: {'shape': torch.Size([]), 'dtype': torch.int64, 'device': device(type='cpu')}
[rank0]: recomputed metadata: {'shape': torch.Size([]), 'dtype': torch.int64, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 22:
[rank0]: saved metadata: {'shape': torch.Size([]), 'dtype': torch.int64, 'device': device(type='cpu')}
[rank0]: recomputed metadata: {'shape': torch.Size([]), 'dtype': torch.int64, 'device': device(type='cuda', index=0)}
```

Please find the full log file attached
[err.llama.log](https://github.com/user-attachments/files/17687399/err.llama.log)

**Comment by mayank31398** [comment]
this uses gradient checkpointing?
can you share the config?

**Comment by murthyrudra** [comment]
Please find the config I am using
[llama-3.1-8b-training.txt](https://github.com/user-attachments/files/17689144/llama-3.1-8b-training.txt)

**Comment by mayank31398** [comment]
```
distributed_args:
  gradient_checkpointing_method: block
  gradient_checkpointing_args:
    use_reentrant: true
```
add this, this is a PyTorch bug

**Comment by murthyrudra** [comment]
Thanks, Now I am getting Cuda out of memory error even with 8 GPUs and batch size of 1. the config is the same with the following modifications
```
distributed_args:
  gradient_checkpointing_method: block
  gradient_checkpointing_args:
    use_reentrant: true
```

Please see the attached log. Specifically, this warning
```
/user/conda/lib/python3.11/site-packages/torch/distributed/fsdp/_init_utils.py:444: UserWarning: FSDP is switching to use `NO_SHARD` instead of ShardingStrategy.FULL_SHARD since the world size is 1.
[err.llama.log](https://github.com/user-attachments/files/17690642/err.llama.log)

```

**Comment by mayank31398** [comment]
are u using 1 GPU?
the log says world size is 1.

**Comment by murthyrudra** [comment]
I tried using 4 and 8 GPUs. The error and warning is the same. I did print
the command after submitting the job. In torchrun the number of GPUs is
either 4 or 8

**Comment by murthyrudra** [comment]
If we see the logs, this is how the device mesh variable looks like
```
DeviceMesh('cuda', [[[0], [1], [2], [3]]], mesh_dim_names=('ddp', 'fsdp', 'tp'))
```

it has identified 4 GPUs yet, FSDP seems to only 1

**Comment by mayank31398** [comment]
is this fixed?
can I close?

**Comment by murthyrudra** [comment]
Hi @mayank31398 could please share the conda environment yaml file? I am still facing the same issue and maybe this could be due to mismatch in library version

**Comment by murthyrudra** [comment]
Seems like there is an Issue with the local environment and not the codebase.
